export const LOAD_TABLE_DATA = 'LOAD_TABLE_DATA'

export const SORT_TABLE_DATA = 'SORT_TABLE_DATA'

export const CHANGE_SETTINGS = 'CHANGE_SETTINGS'

export const CHANGE_SETTINGS_DATE = 'CHANGE_SETTINGS_DATE'

export const CHANGE_SETTINGS_FILTERS = 'CHANGE_SETTINGS_FILTERS'

export const GET_OPTIONS_FIELD = 'GET_OPTIONS_FIELD'

export const ADD_CONDITION = 'ADD_CONDITION'

export const CHANGE_SETTINGS_CONDITION = 'CHANGE_SETTINGS_CONDITION'

export const DELETE_SETTINGS_CONDITION = 'DELETE_SETTINGS_CONDITION'

export const ADD_FILTER = 'ADD_FILTER'
export const ADD_FILTER_ID = 'ADD_FILTER_ID'

export const CHANGE_SETTINGS_FILTER = 'CHANGE_SETTINGS_FILTER'

export const DELETE_SETTINGS_FILTER = 'DELETE_SETTINGS_FILTER'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'
